name: ci

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: supplantr/iniq:latest

      - name: Build and push testrunner
        id: docker_build_testrunner
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.testrunner
          push: true
          tags: supplantr/iniq-testrunner:latest
